version: '3'
services:
  web-proxy:
    image: nginx:stable-alpine
    volumes:
    - ./web-proxy/web-app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  web-app:
    build:
      context: .
      dockerfile: web-app/Dockerfile
