version: '3'
services:
  web-proxy:
    build:
      context: .
      dockerfile: web-proxy/Dockerfile
    ports:
      - "80:80"
  web-app:
    build:
      context: .
      dockerfile: web-app/Dockerfile
